export default [
  {
    id: 1,
    departureTime: "7:15",
    arrivalTime: "13:00",
    departureLocation: "Istanbul",
    arrivalLocation: "Ankara/Otogarı",
    journeyDuration: "5:45",
    price: "110.00",
    features: "",
    seats: {
      row1: [
        { id: "1", empty: true, selected: false, gender: "" },
        { id: "4", empty: false, selected: true, gender: "woman" },
        { id: "7", empty: true, selected: false, gender: "" },
        { id: "10", empty: true, selected: false, gender: "" },
        { id: "13", empty: true, selected: false, gender: "" },
        { id: "16", empty: true, selected: false, gender: "" },
        { id: "19", empty: true, selected: false, gender: "" },
      ],
      row2: [
        { id: "2", empty: false, selected: true, gender: "man" },
        { id: "3", empty: false, selected: true, gender: "woman" },
        { id: "5", empty: true, selected: false, gender: "" },
        { id: "6", empty: true, selected: false, gender: "" },
        { id: "8", empty: true, selected: false, gender: "" },
        { id: "9", empty: true, selected: false, gender: "" },
        { id: "11", empty: true, selected: false, gender: "" },
        { id: "12", empty: false, selected: true, gender: "man" },
        { id: "14", empty: true, selected: false, gender: "" },
        { id: "15", empty: true, selected: false, gender: "" },
        { id: "17", empty: true, selected: false, gender: "" },
        { id: "18", empty: true, selected: false, gender: "" },
        { id: "20", empty: true, selected: false, gender: "" },
        { id: "21", empty: true, selected: false, gender: "" },
      ],
    },
  },
  {
    id: 2,
    departureTime: "8:00",
    arrivalTime: "15:00",
    departureLocation: "Istanbul/Esenler Otogarı",
    arrivalLocation: "Ankara/Otogarı",
    journeyDuration: "7:00",
    price: "110.00",
    features: "",
    seats: {
      row1: [
        { id: "1", empty: true, selected: false, gender: "" },
        { id: "4", empty: true, selected: false, gender: "" },
        { id: "7", empty: true, selected: false, gender: "" },
        { id: "10", empty: true, selected: false, gender: "" },
        { id: "13", empty: true, selected: false, gender: "" },
        { id: "16", empty: false, selected: true, gender: "woman" },
        { id: "19", empty: true, selected: false, gender: "" },
      ],
      row2: [
        { id: "2", empty: false, selected: true, gender: "man" },
        { id: "3", empty: false, selected: true, gender: "woman" },
        { id: "5", empty: true, selected: false, gender: "" },
        { id: "6", empty: true, selected: false, gender: "" },
        { id: "8", empty: true, selected: false, gender: "" },
        { id: "9", empty: true, selected: false, gender: "" },
        { id: "11", empty: true, selected: false, gender: "" },
        { id: "12", empty: false, selected: true, gender: "man" },
        { id: "14", empty: true, selected: false, gender: "" },
        { id: "15", empty: true, selected: false, gender: "" },
        { id: "17", empty: true, selected: false, gender: "" },
        { id: "18", empty: true, selected: false, gender: "" },
        { id: "20", empty: true, selected: false, gender: "" },
        { id: "21", empty: true, selected: false, gender: "" },
      ],
    },
  },
  {
    id: 3,
    departureTime: "7:15",
    arrivalTime: "13:00",
    departureLocation: "Istanbul",
    arrivalLocation: "Ankara/Otogarı",
    journeyDuration: "5:45",
    price: "110.00",
    features: "",
    seats: {
      row1: [
        { id: "1", empty: true, selected: false, gender: "" },
        { id: "4", empty: false, selected: true, gender: "woman" },
        { id: "7", empty: true, selected: false, gender: "" },
        { id: "10", empty: true, selected: false, gender: "" },
        { id: "13", empty: true, selected: false, gender: "" },
        { id: "16", empty: true, selected: false, gender: "" },
        { id: "19", empty: true, selected: false, gender: "" },
      ],
      row2: [
        { id: "2", empty: false, selected: true, gender: "man" },
        { id: "3", empty: false, selected: true, gender: "woman" },
        { id: "5", empty: true, selected: false, gender: "" },
        { id: "6", empty: true, selected: false, gender: "" },
        { id: "8", empty: true, selected: false, gender: "" },
        { id: "9", empty: true, selected: false, gender: "" },
        { id: "11", empty: true, selected: false, gender: "" },
        { id: "12", empty: false, selected: true, gender: "man" },
        { id: "14", empty: true, selected: false, gender: "" },
        { id: "15", empty: true, selected: false, gender: "" },
        { id: "17", empty: true, selected: false, gender: "" },
        { id: "18", empty: true, selected: false, gender: "" },
        { id: "20", empty: true, selected: false, gender: "" },
        { id: "21", empty: true, selected: false, gender: "" },
      ],
    },
  },
  {
    id: 4,
    departureTime: "7:15",
    arrivalTime: "13:00",
    departureLocation: "Istanbul",
    arrivalLocation: "Ankara/Otogarı",
    journeyDuration: "5:45",
    price: "110.00",
    features: "",
    seats: {
      row1: [
        { id: "1", empty: true, selected: false, gender: "" },
        { id: "4", empty: true, selected: false, gender: "" },
        { id: "7", empty: true, selected: false, gender: "" },
        { id: "10", empty: true, selected: false, gender: "" },
        { id: "13", empty: true, selected: false, gender: "" },
        { id: "16", empty: true, selected: false, gender: "" },
        { id: "19", empty: true, selected: false, gender: "" },
      ],
      row2: [
        { id: "2", empty: true, selected: false, gender: "" },
        { id: "3", empty: true, selected: false, gender: ""},
        { id: "5", empty: true, selected: false, gender: "" },
        { id: "6", empty: true, selected: false, gender: "" },
        { id: "8", empty: true, selected: false, gender: "" },
        { id: "9", empty: true, selected: false, gender: "" },
        { id: "11", empty: true, selected: false, gender: "" },
        { id: "12", empty: true, selected: false, gender: "" },
        { id: "14", empty: true, selected: false, gender: "" },
        { id: "15", empty: true, selected: false, gender: "" },
        { id: "17", empty: true, selected: false, gender: "" },
        { id: "18", empty: true, selected: false, gender: "" },
        { id: "20", empty: true, selected: false, gender: "" },
        { id: "21", empty: true, selected: false, gender: "" },
      ],
    },
  },
];
